In [1]:
####Diabetes Data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
import os
print(os.getcwd())

C:\Users\toshi\Downloads\01_DataScience\data science practical\py-cmpt ML


In [3]:
os.chdir('C:\\Users\\toshi\\Downloads\\01_DataScience\\AI\\Datasets')

In [4]:
###importing the DataSet
df=pd.read_csv("Diabetes.csv")

In [5]:
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [6]:
array=df.values
array

array([[6, 148, 72, ..., 0.627, 50, 'YES'],
       [1, 85, 66, ..., 0.35100000000000003, 31, 'NO'],
       [8, 183, 64, ..., 0.672, 32, 'YES'],
       ...,
       [5, 121, 72, ..., 0.245, 30, 'NO'],
       [1, 126, 60, ..., 0.349, 47, 'YES'],
       [1, 93, 70, ..., 0.315, 23, 'NO']], dtype=object)

In [7]:
X=array[:,0:8]#ivs for train
X

array([[6, 148, 72, ..., 33.6, 0.627, 50],
       [1, 85, 66, ..., 26.6, 0.35100000000000003, 31],
       [8, 183, 64, ..., 23.3, 0.672, 32],
       ...,
       [5, 121, 72, ..., 26.2, 0.245, 30],
       [1, 126, 60, ..., 30.1, 0.349, 47],
       [1, 93, 70, ..., 30.4, 0.315, 23]], dtype=object)

In [8]:
y=array[:,8]##Dv
y

array(['YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'YES', 'YES',
       'NO', 'YES', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES',
       'NO', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO',
       'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'YES', 'YES',
       'NO', 'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO',
       'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO',
       'YES', 'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', 'YES',
       'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO',
       'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO',
       'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'YES', 'YES', 'NO',
       'NO', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO',
       'NO', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES', 'YES', 'YES', 'YES',
       'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'

In [9]:
test_size=0.33

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
##pip install U Scikit -learn
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size)

# KNN

In [12]:
from sklearn.neighbors  import KNeighborsClassifier

In [13]:
model = KNeighborsClassifier()

In [14]:
model.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [15]:
prediction=model.predict(X_test)

In [16]:
outcome=y_test
outcome

array(['YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'YES', 'NO',
       'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO',
       'NO', 'YES', 'NO', 'YES', 'YES', 'NO', 'YES', 'YES', 'NO', 'NO',
       'NO', 'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO', 'NO',
       'NO', 'YES', 'NO', 'NO', 'YES', 'YES', 'NO', 'YES', 'NO', 'YES',
       'NO', 'YES', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO', 'NO', 'NO',
       'NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'YES', 'YES', 'NO', 'NO',
       'YES', 'YES', 'YES', 'NO', 'NO', 'YES', 'YES', 'NO', 'YES', 'YES',
       'NO', 'YES', 'YES', 'YES', 'YES', 'NO', 'NO', 'NO', 'NO', 'YES',
       'YES', 'YES', 'YES', 'YES', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO',
       'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO',
       'YES', 'NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO',
       'NO', 'NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'YES', 'NO', 'YES',
       'YES', 'NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', '

In [17]:
from sklearn import metrics

In [18]:
print(metrics.accuracy_score(outcome,prediction))###true value v/s predicted values

0.7047244094488189


In [19]:
###Again
model = KNeighborsClassifier(7)

In [20]:
model.fit(X_train,y_train)
prediction=model.predict(X_test)
outcome=y_test

In [21]:
print(metrics.accuracy_score(outcome,prediction))####true value v/s predicted values

0.6968503937007874


# Decision Tree

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
model= DecisionTreeClassifier()

In [24]:
model.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
prediction=model.predict(X_test)

In [26]:
outcome=y_test

In [27]:
print(metrics.accuracy_score(prediction,outcome))

0.7086614173228346


# Feature Selection

In [28]:
from sklearn.feature_selection import SelectKBest ,chi2

In [29]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size)

In [30]:
print(df.shape)

(768, 9)


In [31]:
## we have 8 feature or ivs &1 Dv in other word we are using all feature
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [32]:
test=SelectKBest(score_func=chi2,k=4)##select top 4 features
fit=test.fit(X,y)


In [33]:
fit

SelectKBest(k=4, score_func=<function chi2 at 0x00000257286BA488>)

In [34]:
np.set_printoptions(precision=3)

In [35]:
print(fit.scores_)#give the feature of all of the scores
print("********************Higher the score better the features predict*******************")

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]
********************Higher the score better the features predict*******************


In [36]:
df.columns

Index([' Number of times pregnant', ' Plasma glucose concentration',
       ' Diastolic blood pressure', ' Triceps skin fold thickness',
       ' 2-Hour serum insulin', ' Body mass index',
       ' Diabetes pedigree function', ' Age (years)', ' Class variable'],
      dtype='object')

In [37]:
features=fit.transform(X)

In [38]:
print(features[0:5,:])#print 5 rows all features which is only 4 cols or 4 features 

[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]


# LogisticRegression

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [40]:
logreg=LogisticRegression()

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [42]:
#this is using all the features and we had not done the feature selection here
logreg.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [43]:
logreg.score(X_test,y_test)#this give the accuracy

0.765625

In [44]:
#so rerun with the feature selection with only  selected features
logreg=LogisticRegression()

In [45]:
X_train,y_train,X_test,y_test=train_test_split(features,y)# we are using features instead of X

In [46]:
logreg.fit(X_train,y_train)

ValueError: bad input shape (192, 4)

In [ ]:
logreg.score(X_test,y_test)#it may worsening  here sometimes

In [ ]:
##recursive feature elimination,feature selection technique
##give the combination of features which give the better accuracy

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [48]:
logreg=LogisticRegression()

In [49]:
from sklearn.feature_selection import RFE

In [50]:
#rfe=RFE(model,3)# v will use 3 features only best combination of 3 features
rfe=RFE(logreg,3)#v will use 3 features only best combination of 3 features

In [51]:
import sklearn 

In [52]:
print(' The scikit-learn version is :{}'.format(sklearn))

 The scikit-learn version is :<module 'sklearn' from 'C:\\Users\\toshi\\Anaconda3\\lib\\site-packages\\sklearn\\__init__.py'>


In [53]:
fit=rfe.fit(X,y)

In [54]:
print("Number of features:%d"% fit.n_features_)#gvs num of features

Number of features:3


In [55]:
print("Selected features:%s"% fit.support_)#givs bool vals,which features have been selected by feature selection mod

Selected features:[ True False False False False  True  True False]


In [56]:
print("Feature.Ranking:%s"%fit.ranking_)#gives

Feature.Ranking:[1 2 3 5 6 1 1 4]


In [57]:
print("Feature sorted by their rank:")

Feature sorted by their rank:


In [58]:
print(sorted(zip(map(lambda x:round(x,4),rfe.ranking_))))

[(1,), (1,), (1,), (2,), (3,), (4,), (5,), (6,)]


# PCA####DIM Reduction Techniq

In [59]:
#unlike select KBest it is not just eliminating the features
#but it is created new features called as components
#so it is referred as dim techniq.

In [60]:
df.head()

Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      0              23.3                        0.672   
3                     94              28.1                        0.167   
4                    168              43.1                        2.288   

    Age (years)  Class variable  
0            50             YES  
1            31              NO  
2            32             YES  
3            21              NO  
4            33             YES

In [61]:
from sklearn.decomposition import PCA
pca=PCA(n_components=None)
fit=pca.fit(X)
print('Explained Varience Ratio %s:',fit.explained_variance_ratio_)
#[8.885e-01 6.159e-02 2.579e-02 1.309e-02 7.441e-03 3.026e-03 5.124e-04
 #6.793e-06]
#first PC explain 88%
#first2PCs explain 88+6=94% and soo on

Explained Varience Ratio %s: [8.885e-01 6.159e-02 2.579e-02 1.309e-02 7.441e-03 3.026e-03 5.124e-04
 6.793e-06]


In [62]:
print(fit.components_)

[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02
   5.372e-04 -3.565e-03]
 [-2.265e-02 -9.722e-01 -1.419e-01  5.786e-02  9.463e-02 -4.697e-02
  -8.168e-04 -1.402e-01]
 [-2.246e-02  1.434e-01 -9.225e-01 -3.070e-01  2.098e-02 -1.324e-01
  -6.400e-04 -1.255e-01]
 [-4.905e-02  1.198e-01 -2.627e-01  8.844e-01 -6.555e-02  1.928e-01
   2.699e-03 -3.010e-01]
 [ 1.516e-01 -8.794e-02 -2.322e-01  2.600e-01 -1.723e-04  2.147e-02
   1.641e-03  9.205e-01]
 [-5.047e-03  5.074e-02  7.564e-02  2.214e-01 -6.133e-03 -9.708e-01
  -2.029e-03 -1.511e-02]
 [ 9.867e-01  8.834e-04 -1.230e-03 -3.764e-04  1.423e-03 -2.730e-03
  -6.344e-03 -1.626e-01]
 [ 6.101e-03 -8.255e-04  5.209e-04 -2.549e-03 -2.690e-04 -2.673e-03
   1.000e+00 -1.953e-03]]


In [63]:
pca=PCA(n_components=3)
fit=pca.fit(X)
print('Explained Variance Ratio %s:',fit.explained_variance_ratio_)
#Explained Varience Ratio %s:[0.889 0.062 0.026]

Explained Variance Ratio %s: [0.889 0.062 0.026]


In [64]:
'''
first set of component capture 88.9% of the varience 
and secound set of components 6%
this is the first component

[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02
   5.372e-04 -3.565e-03]
and soo onn....
'''

'\nfirst set of component capture 88.9% of the varience \nand secound set of components 6%\nthis is the first component\n\n[[-2.022e-03  9.781e-02  1.609e-02  6.076e-02  9.931e-01  1.401e-02\n   5.372e-04 -3.565e-03]\nand soo onn....\n'

In [65]:
#Extra Tree Classifier ###Fourth Technique

In [66]:
from sklearn.ensemble import ExtraTreesClassifier
model=ExtraTreesClassifier()
model.fit(X,y)
print(model.feature_importances_)
#higher the vals the better the feature are
#drop the low val features

[0.105 0.227 0.098 0.079 0.079 0.14  0.113 0.159]


In [67]:
#preprocessing techniques###
seed=np.random.seed(3)
test_size=0.33
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=seed)
print(df.head())

    Number of times pregnant   Plasma glucose concentration  \
0                          6                            148   
1                          1                             85   
2                          8                            183   
3                          1                             89   
4                          0                            137   

    Diastolic blood pressure   Triceps skin fold thickness  \
0                         72                            35   
1                         66                            29   
2                         64                             0   
3                         66                            23   
4                         40                            35   

    2-Hour serum insulin   Body mass index   Diabetes pedigree function  \
0                      0              33.6                        0.627   
1                      0              26.6                        0.351   
2                      

In [68]:
model=LogisticRegression()
model.fit(X_train,y_train)
print(model.score(X_test,y_test))#normal model wo fes selection 

0.71875


In [69]:
rfe=RFE(model,6)#6is hyper par
training =rfe.fit(X_train,y_train)
applied=training.transform(X_train)
print(applied)

[[0.00e+00 5.70e+01 6.00e+01 2.17e+01 7.35e-01 6.70e+01]
 [0.00e+00 1.80e+02 9.00e+01 3.65e+01 3.14e-01 3.50e+01]
 [1.00e+00 9.60e+01 1.22e+02 2.24e+01 2.07e-01 2.70e+01]
 ...
 [4.00e+00 9.00e+01 0.00e+00 2.80e+01 6.10e-01 3.10e+01]
 [1.00e+00 1.11e+02 8.60e+01 3.01e+01 1.43e-01 2.30e+01]
 [6.00e+00 1.15e+02 6.00e+01 3.37e+01 2.45e-01 4.00e+01]]


In [89]:
model2=LogisticRegression()
model2.fit(applied,y_train)#this is a transformed data
testdata=training.transform(X_test)
model2.score(testdata,y_test)

0.7239583333333334

In [90]:
me=np.array([0,150,70,30,0,400.5])#new vals for predictions
me

array([  0. , 150. ,  70. ,  30. ,   0. , 400.5])

In [91]:
me_adjusted=me.reshape(1,-1)# in new vers of numpy this is reaq. when v have 1 obs 
me_adjusted

array([[  0. , 150. ,  70. ,  30. ,   0. , 400.5]])

In [92]:
me_adjusted=training.transform(me_adjusted)
me_adjusted#only 6 are left

ValueError: X has a different shape than during fitting.

In [93]:
model2.predict(me_adjusted)

array(['YES'], dtype=object)

In [94]:
#Dummy  Vars & Encoders

In [95]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [96]:
dataset=['Pizza','Burger','bread','bread','bread','Burger','Pizza','Burger']
dataset

['Pizza', 'Burger', 'bread', 'bread', 'bread', 'Burger', 'Pizza', 'Burger']

In [97]:
values=array(dataset)
print(values)

['Pizza' 'Burger' 'bread' 'bread' 'bread' 'Burger' 'Pizza' 'Burger']


In [98]:
label_encoder=LabelEncoder()
integer_encoded=label_encoder.fit_transform(values)
print(integer_encoded)

[1 0 2 2 2 0 1 0]


In [99]:
onehot=OneHotEncoder(sparse=False)
integer_encoded=integer_encoded.reshape(len(integer_encoded),1)
onehot_encoded=onehot.fit_transform(integer_encoded)
print(onehot_encoded)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [100]:
inverted_result=label_encoder.inverse_transform([argmax(onehot_encoded[0,:])])
print(inverted_result)

['Pizza']


C:\Users\toshi\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [101]:
import pandas as pd
pd.get_dummies(dataset)


Burger  Pizza  bread
0       0      1      0
1       1      0      0
2       0      0      1
3       0      0      1
4       0      0      1
5       1      0      0
6       0      1      0
7       1      0      0

In [102]:
#implement of OneHotEncoding

In [103]:
import keras

C:\Users\toshi\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [104]:
from keras.utils import to_categorical


In [105]:
myarray=array(dataset)

In [106]:
integer_encoded=label_encoder.fit_transform(myarray)
print(integer_encoded)

[1 0 2 2 2 0 1 0]


In [107]:
kerasencoded=to_categorical(integer_encoded)
print(kerasencoded)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [108]:
#handling missing vals in keras
#ln[8]


In [109]:
import pandas 
import os

In [110]:
os.chdir("C:\\Users\\toshi\\Downloads\\01_DataScience\\AI\\Datasets\\")

In [111]:
dataset=pd.read_csv("pima-indians-diabetes.data.csv")

In [112]:
print(dataset.head(15))
#ntc the 5th colm is bmi
#and is gen not 0 but v have a lot of  0 vals

     6  148  72  35    0  33.6  0.627  50  1
0    1   85  66  29    0  26.6  0.351  31  0
1    8  183  64   0    0  23.3  0.672  32  1
2    1   89  66  23   94  28.1  0.167  21  0
3    0  137  40  35  168  43.1  2.288  33  1
4    5  116  74   0    0  25.6  0.201  30  0
5    3   78  50  32   88  31.0  0.248  26  1
6   10  115   0   0    0  35.3  0.134  29  0
7    2  197  70  45  543  30.5  0.158  53  1
8    8  125  96   0    0   0.0  0.232  54  1
9    4  110  92   0    0  37.6  0.191  30  0
10  10  168  74   0    0  38.0  0.537  34  1
11  10  139  80   0    0  27.1  1.441  57  0
12   1  189  60  23  846  30.1  0.398  59  1
13   5  166  72  19  175  25.8  0.587  51  1
14   7  100   0   0    0  30.0  0.484  32  1


In [113]:
print(dataset[[1,2,3,4,5]].head())#first 5 rows and coloumns

KeyError: '[1 2 3 4 5] not in index'

In [114]:
dataset.head(5)==0

6    148     72     35      0   33.6  0.627     50      1
0  False  False  False  False   True  False  False  False   True
1  False  False  False   True   True  False  False  False  False
2  False  False  False  False  False  False  False  False   True
3   True  False  False  False  False  False  False  False  False
4  False  False  False   True   True  False  False  False   True

In [115]:
dataset.head(5)==0.sum()

SyntaxError: invalid syntax (<ipython-input-115-b569b483a75c>, line 1)

In [116]:
print((dataset[[1,2,3,4,5]]==0).sum())
#this give the nums of the 0 vals v hv in first 5 cols
#ntc 3 & 4 hv unusual nums of 0s
#3rd col is triceps skinfold thickness
# 4th colm is 2-hrs serum 

KeyError: '[1 2 3 4 5] not in index'

In [117]:
#missing vals to nans
import numpy as np 
dataset[[1,2,3,4,5]]=dataset[[1,2,3,4,5]].replace(0,np.Nan)
print(dataset.head(15))


KeyError: '[1 2 3 4 5] not in index'

# Linear Discriminant Analysis

In [118]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [119]:
from sklearn.model_selection import KFold

In [120]:
from sklearn.model_selection import cross_val_score


In [121]:
values=dataset.values

In [122]:
X=values[:,0:8]
y=values[:,8]

In [123]:
model=LinearDiscriminantAnalysis()
kfold=KFold(n_splits=3,random_state=7)
result=cross_val_score (model,X,y,cv=kfold,scoring="accuracy")
print(result.mean())#we should get this#input contain NaN,infinity or a values too large for dtyps('float64')

0.7744995915032679


In [124]:
#remaining pages 25-28