In [12]:
##Rescaling and normalisation
##machine learning put a higher weightage on feature which have higher scale
import os
import pandas as pd
import numpy as np


In [13]:
os.chdir("C:\\Users\\toshi\\Downloads\\01_DataScience\\AI\\Datasets")

In [14]:
df=pd.read_csv("diabetes2.csv")

In [15]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [16]:
array=df.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [46]:
X=array[:,0:8]
y=array[:,8]

In [47]:
seed=7

In [48]:
from sklearn.preprocessing import MinMaxScaler

In [49]:
scaler=MinMaxScaler(feature_range=(0,1))# scaling data between 0-1

In [50]:
rescaled=scaler.fit_transform(X)
np.set_printoptions(precision=3)
print(rescaled[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [51]:
print(X)

[[  6.    148.     72.    ...  33.6     0.627  50.   ]
 [  1.     85.     66.    ...  26.6     0.351  31.   ]
 [  8.    183.     64.    ...  23.3     0.672  32.   ]
 ...
 [  5.    121.     72.    ...  26.2     0.245  30.   ]
 [  1.    126.     60.    ...  30.1     0.349  47.   ]
 [  1.     93.     70.    ...  30.4     0.315  23.   ]]


In [52]:
df.head(2)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70          0.0             1.9      0.076   
1            7.8              0.88          0.0             2.6      0.098   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   

   alcohol  quality  
0      9.4        5  
1      9.8        5

In [53]:
##Standardization ,mean of 0 ,SD of 1 ,gaussian distrb
## LR,Log ReGG., LDA
from sklearn.preprocessing import StandardScaler 
scaler2=StandardScaler()
rescaled2=scaler2.fit_transform(X)
print(rescaled2[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


In [54]:
#vals with a mean of 0 and SD of 1
#take each feature values
#calculate  the mean of each vals
#sub. the mean
#thn divide by SD
#then we get these values
######this is a 2nd preProcessing Technique#####

In [55]:
##Normalisation:-when v have lots of 0&missing vals
## or atts of varying scale used in NNs,KNNs
##rescaling each obs to a len of 1 called unit norm in linear alg
from sklearn.preprocessing import Normalizer
scaler3=Normalizer()
rescaled3=scaler3.fit_transform(X)
print(rescaled3[0:5,:])

[[0.034 0.828 0.403 0.196 0.    0.188 0.004 0.28 ]
 [0.008 0.716 0.556 0.244 0.    0.224 0.003 0.261]
 [0.04  0.924 0.323 0.    0.    0.118 0.003 0.162]
 [0.007 0.588 0.436 0.152 0.622 0.186 0.001 0.139]
 [0.    0.596 0.174 0.152 0.731 0.188 0.01  0.144]]


In [56]:
##Binarizer:-make data binary
#set a thresold
#anything above thresold is 1 or 0 and viceversa
from sklearn.preprocessing import Binarizer
scaler4=Binarizer(threshold=0.0)#thr is 0
rescaled4=scaler4.fit_transform(X)
print(rescaled[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]


In [57]:
#Feature Scaling Project
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error,r2_score


In [58]:
df=pd.read_csv("Wine-quality-dataset.csv")

In [59]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [60]:
y=df.quality
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [61]:
X=df.drop('quality',axis=1)
X.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [62]:
from sklearn.model_selection import train_test_split
test_size=0.33

In [63]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size,random_state=123,stratify=y)

In [64]:
#for reproduceability
#stratified sampling 
clf=Ridge()
clf.fit(X_train,y_train)
prediction=clf.predict(X_test)
print(r2_score(y_test,prediction))
print(mean_squared_error(y_test,prediction))

0.3327115369237549
0.43175179698150934


In [74]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X_train_Scaled=scaler.fit_transform(X_train)
X_test_Scaled=scaler.fit_transform(X_test)

In [80]:
clf2=Ridge()
clf2.fit(X_train_Scaled,y_train)
prediction2=clf2.predict(X_test_Scaled)
print(r2_score(y_test,prediction2))
print(mean_squared_error(y_test,prediction2)) #slightly better

0.33210557672989494
0.4321438679029699
